from django.contrib import admin

# Register your models here.
from .models import (
    LedgerEntry, AuditLog, FinancialReport,
    UserActivityLog, SystemHealthCheck
)

@admin.register(LedgerEntry)
class LedgerEntryAdmin(admin.ModelAdmin):
    list_display = ('ledger_id', 'get_user_email', 'transaction_type', 
                   'amount', 'balance_before', 'balance_after', 
                   'source_app', 'is_verified', 'created_at')
    list_filter = ('transaction_type', 'source_app', 'is_verified', 'created_at')
    search_fields = ('user__email', 'reference_id', 'description', 'ledger_id')
    readonly_fields = ('ledger_id', 'balance_before', 'balance_after',
                      'is_verified', 'verified_by', 'verified_at',
                      'verification_notes', 'created_at')
    
    def get_user_email(self, obj):
        return obj.user.email
    get_user_email.short_description = 'User'
    
    def get_queryset(self, request):
        return super().get_queryset(request).select_related('user', 'verified_by')

@admin.register(AuditLog)
class AuditLogAdmin(admin.ModelAdmin):
    list_display = ('audit_id', 'get_admin_email', 'action', 
                   'target_object', 'status', 'created_at')
    list_filter = ('action', 'status', 'created_at')
    search_fields = ('admin__email', 'target_object', 'target_model', 'audit_id')
    readonly_fields = ('audit_id', 'created_at')
    
    def get_admin_email(self, obj):
        return obj.admin.email
    get_admin_email.short_description = 'Admin'
    
    def get_queryset(self, request):
        return super().get_queryset(request).select_related('admin')

@admin.register(FinancialReport)
class FinancialReportAdmin(admin.ModelAdmin):
    list_display = ('report_id', 'title', 'report_type', 'report_format',
                   'get_generated_by_email', 'is_generated', 'created_at')
    list_filter = ('report_type', 'report_format', 'is_generated', 'created_at')
    search_fields = ('title', 'report_id', 'generated_by__email')
    readonly_fields = ('report_id', 'is_generated', 'generation_started_at',
                      'generation_completed_at', 'generation_duration',
                      'file_size', 'created_at', 'expires_at')
    
    def get_generated_by_email(self, obj):
        return obj.generated_by.email
    get_generated_by_email.short_description = 'Generated By'
    
    def get_queryset(self, request):
        return super().get_queryset(request).select_related('generated_by')

@admin.register(UserActivityLog)
class UserActivityLogAdmin(admin.ModelAdmin):
    list_display = ('activity_id', 'get_user_email', 'activity_type', 
                   'description', 'ip_address', 'created_at')
    list_filter = ('activity_type', 'device_type', 'created_at')
    search_fields = ('user__email', 'description', 'ip_address', 'activity_id')
    readonly_fields = ('activity_id', 'created_at')
    
    def get_user_email(self, obj):
        return obj.user.email
    get_user_email.short_description = 'User'
    
    def get_queryset(self, request):
        return super().get_queryset(request).select_related('user')

@admin.register(SystemHealthCheck)
class SystemHealthCheckAdmin(admin.ModelAdmin):
    list_display = ('check_id', 'check_type', 'status', 
                   'response_time', 'success_rate', 'created_at')
    list_filter = ('check_type', 'status', 'created_at')
    search_fields = ('check_id', 'message')
    readonly_fields = ('check_id', 'created_at')

