# Generated by Django 6.0 on 2026-02-28 20:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('STARTER', 'Starter Package'), ('GROWTH', 'Growth Package'), ('PREMIUM', 'Premium Package'), ('CUSTOM', 'Custom Package')], default='STARTER', max_length=20)),
                ('category', models.CharField(choices=[('CRYPTO_MINING', 'Crypto Mining'), ('FOREX_TRADING', 'Forex Trading'), ('DUAL_STRATEGY', 'Dual Strategy (Mining + Forex)')], default='DUAL_STRATEGY', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('min_amount', models.DecimalField(decimal_places=8, default=Decimal('50.00'), help_text='Minimum investment amount in USD', max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Maximum investment amount in USD (null for unlimited)', max_digits=20, null=True)),
                ('min_return_multiplier', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum return multiplier (e.g., 5 for 5x)', max_digits=10)),
                ('max_return_multiplier', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Maximum return multiplier (e.g., 10 for 10x)', max_digits=10)),
                ('return_period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='WEEKLY', max_length=20)),
                ('min_duration_days', models.PositiveIntegerField(default=7, help_text='Minimum recommended duration in days')),
                ('max_duration_days', models.PositiveIntegerField(blank=True, help_text='Maximum recommended duration in days', null=True)),
                ('is_flexible_duration', models.BooleanField(default=False, help_text='Can users withdraw anytime?')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features/benefits (JSON array)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk')], default='MODERATE', max_length=20)),
                ('performance_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Performance fee percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('total_investors', models.PositiveIntegerField(default=0)),
                ('total_invested', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_profits_paid', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Success rate percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('OPPORTUNITY', 'Investment Opportunity'), ('MARKET_UPDATE', 'Market Update'), ('PLAN_UPDATE', 'Plan Update'), ('PERFORMANCE', 'Performance Report'), ('MAINTENANCE', 'Maintenance Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_for_all_users', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='investment_alerts', to=settings.AUTH_USER_MODEL)),
                ('target_plans', models.ManyToManyField(blank=True, related_name='alerts', to='investments.investmentplan')),
            ],
            options={
                'verbose_name': 'Investment Alert',
                'verbose_name_plural': 'Investment Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='investments.investmentplan')),
            ],
            options={
                'verbose_name': 'Plan FAQ',
                'verbose_name_plural': 'Plan FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('average_return', models.DecimalField(decimal_places=2, help_text='Average return percentage for the period', max_digits=10)),
                ('total_invested', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_profits', models.DecimalField(decimal_places=8, max_digits=20)),
                ('active_investments', models.PositiveIntegerField()),
                ('completed_investments', models.PositiveIntegerField()),
                ('market_condition', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('VOLATILE', 'Volatile'), ('STABLE', 'Stable')], default='STABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='investments.investmentplan')),
            ],
            options={
                'verbose_name': 'Plan Performance',
                'verbose_name_plural': 'Plan Performances',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('expected_return_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_total', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('current_value', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('total_profit', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_profit_date', models.DateTimeField(blank=True, null=True)),
                ('next_profit_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('withdrawal_status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Withdrawal Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Withdrawn'), ('DENIED', 'Withdrawal Denied')], default='NOT_REQUESTED', max_length=20)),
                ('early_withdrawal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee percentage for early withdrawal', max_digits=10)),
                ('referral_bonus_paid', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='investments.investmentplan')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_investments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Investment',
                'verbose_name_plural': 'User Investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('WALLET', 'Wallet Balance'), ('CRYPTO', 'Cryptocurrency'), ('BANK', 'Bank Transfer')], default='WALLET', max_length=50)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='investments.userinvestment')),
            ],
            options={
                'verbose_name': 'Profit Withdrawal',
                'verbose_name_plural': 'Profit Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
