# Generated by Django 6.0 on 2026-02-28 20:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default bonus amount in USD', max_digits=10)),
                ('minimum_deposit_for_bonus', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum deposit amount to qualify for referral bonus', max_digits=10)),
                ('enable_tiered_bonuses', models.BooleanField(default=False)),
                ('tiered_bonus_settings', models.JSONField(blank=True, default=dict, help_text="Tiered bonus structure (e.g., {'tier1': {'min_referrals': 5, 'bonus': 7.50}})")),
                ('max_referrals_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum number of referrals per user (null for unlimited)', null=True)),
                ('max_bonus_per_user', models.DecimalField(blank=True, decimal_places=8, help_text='Maximum total bonus a user can earn (null for unlimited)', max_digits=20, null=True)),
                ('bonus_withdrawal_enabled', models.BooleanField(default=True)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('withdrawal_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Bonus Settings',
                'verbose_name_plural': 'Referral Bonus Settings',
            },
        ),
        migrations.CreateModel(
            name='BonusWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus Wallet',
                'verbose_name_plural': 'Bonus Wallets',
            },
        ),
        migrations.CreateModel(
            name='UserReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('custom_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('active_referrals', models.PositiveIntegerField(default=0)),
                ('total_bonus_earned', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_generate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Referral Code',
                'verbose_name_plural': 'User Referral Codes',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EARNED', 'Earned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('referred_user_deposited', models.BooleanField(default=False)),
                ('referred_user_deposit_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('bonus_paid', models.BooleanField(default=False)),
                ('bonus_paid_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_transaction_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
