# Generated by Django 6.0 on 2026-02-28 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_type', models.CharField(choices=[('DATABASE', 'Database'), ('CACHE', 'Cache'), ('STORAGE', 'Storage'), ('API', 'API'), ('PAYMENT_GATEWAY', 'Payment Gateway'), ('EMAIL_SERVICE', 'Email Service'), ('FULL', 'Full System')], max_length=50)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('OFFLINE', 'Offline')], max_length=20)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('success_rate', models.FloatField(help_text='Success rate percentage')),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Health Check',
                'verbose_name_plural': 'System Health Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('QUARTERLY_SUMMARY', 'Quarterly Summary'), ('YEARLY_SUMMARY', 'Yearly Summary'), ('USER_ACTIVITY', 'User Activity'), ('DEPOSIT_REPORT', 'Deposit Report'), ('WITHDRAWAL_REPORT', 'Withdrawal Report'), ('INVESTMENT_REPORT', 'Investment Report'), ('REFERRAL_REPORT', 'Referral Report'), ('CUSTOM', 'Custom Report')], max_length=50)),
                ('report_format', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], default='JSON', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('download_url', models.URLField(blank=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_duration', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encryption_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SUSPEND', 'Suspend'), ('ACTIVATE', 'Activate'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('target_object', models.CharField(max_length=255)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('changes_before', models.JSONField(blank=True, default=dict)),
                ('changes_after', models.JSONField(blank=True, default=dict)),
                ('changes_summary', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='reporting_a_admin_i_340c78_idx'), models.Index(fields=['action', 'created_at'], name='reporting_a_action_83e443_idx'), models.Index(fields=['target_model', 'created_at'], name='reporting_a_target__49b604_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INVESTMENT', 'Investment'), ('PROFIT', 'Profit'), ('REFERRAL_BONUS', 'Referral Bonus'), ('FEE', 'Fee'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source_app', models.CharField(choices=[('WALLET', 'Wallet'), ('INVESTMENT', 'Investment'), ('REFERRAL', 'Referral'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'permissions': [('can_verify_ledger', 'Can verify ledger entries')],
                'indexes': [models.Index(fields=['user', 'created_at'], name='reporting_l_user_id_5f2bca_idx'), models.Index(fields=['transaction_type', 'created_at'], name='reporting_l_transac_798373_idx'), models.Index(fields=['source_app', 'created_at'], name='reporting_l_source__f828dd_idx'), models.Index(fields=['reference_id'], name='reporting_l_referen_d1f395_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('DEPOSIT_INITIATED', 'Deposit Initiated'), ('DEPOSIT_COMPLETED', 'Deposit Completed'), ('INVESTMENT_STARTED', 'Investment Started'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('REFERRAL_SIGNUP', 'Referral Signup'), ('TICKET_CREATED', 'Support Ticket Created'), ('TICKET_REPLIED', 'Ticket Replied'), ('NOTIFICATION_READ', 'Notification Read'), ('PAGE_VIEW', 'Page View')], max_length=50)),
                ('description', models.TextField()),
                ('page_url', models.URLField(blank=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='reporting_u_user_id_8433fc_idx'), models.Index(fields=['activity_type', 'created_at'], name='reporting_u_activit_113b32_idx'), models.Index(fields=['ip_address', 'created_at'], name='reporting_u_ip_addr_45f916_idx')],
            },
        ),
    ]
