# Generated by Django 6.0 on 2026-02-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code_sent_at',
            new_name='email_verification_sent_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='phone_verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_income', models.CharField(blank=True, choices=[('UNDER_25K', 'Under $25,000'), ('25K_50K', '$25,000 - $50,000'), ('50K_100K', '$50,000 - $100,000'), ('100K_250K', '$100,000 - $250,000'), ('OVER_250K', 'Over $250,000')], max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Student'), ('RETIRED', 'Retired')], max_length=20, null=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10, null=True)),
                ('investment_goal', models.CharField(blank=True, choices=[('SHORT_TERM', 'Short-term Growth (1-3 years)'), ('MEDIUM_TERM', 'Medium-term Growth (3-7 years)'), ('LONG_TERM', 'Long-term Growth (7+ years)'), ('RETIREMENT', 'Retirement Planning'), ('WEALTH_PRESERVATION', 'Wealth Preservation')], max_length=30, null=True)),
                ('investment_experience', models.TextField(blank=True, null=True)),
                ('selected_plan_id', models.IntegerField(blank=True, null=True)),
                ('selected_plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_privacy_policy', models.BooleanField(default=False)),
                ('accepted_risk_disclosure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Profile',
                'verbose_name_plural': 'Investment Profiles',
            },
        ),
    ]
