# Generated by Django 6.0 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_verification_code_sent_at_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_investment_limit',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Daily investment limit in USD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_investment_total',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_investment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspicious_activity_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
