# Generated by Django 6.0 on 2026-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_daily_investment_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_completed_at',
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_investment_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily investment limit in USD', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_investment_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
