# Generated by Django 6.0 on 2026-03-04 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='actually_paid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['payment_id'], name='wallet_depo_payment_638dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='wallet_depo_status_931183_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='wallet_depo_user_id_426dda_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='wallet_depo_created_2d0711_idx'),
        ),
    ]
