# Generated by Django 6.0 on 2026-02-28 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('ACCOUNT_REGISTRATION', 'Account Registration'), ('LOGIN', 'Login'), ('ACCOUNT_UPDATE', 'Account Update'), ('DEPOSIT_CONFIRMED', 'Deposit Confirmed'), ('INVESTMENT_STARTED', 'Investment Started'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('PROFIT_CREDITED', 'Profit Credited'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('ACCOUNT_SUSPENSION', 'Account Suspension'), ('ACCOUNT_BAN', 'Account Ban'), ('PASSWORD_RESET', 'Password Reset'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_ALERT', 'Security Alert'), ('REFERRAL_BONUS', 'Referral Bonus'), ('SYSTEM_UPDATE', 'System Update')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_template', models.TextField(help_text='HTML template with {{variables}}')),
                ('text_template', models.TextField(help_text='Plain text template with {{variables}}')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('ACCOUNT_REGISTRATION', 'Account Registration'), ('LOGIN', 'Login'), ('ACCOUNT_UPDATE', 'Account Update'), ('DEPOSIT_CONFIRMED', 'Deposit Confirmed'), ('INVESTMENT_STARTED', 'Investment Started'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('PROFIT_CREDITED', 'Profit Credited'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('ACCOUNT_SUSPENSION', 'Account Suspension'), ('ACCOUNT_BAN', 'Account Ban'), ('PASSWORD_RESET', 'Password Reset'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_ALERT', 'Security Alert'), ('REFERRAL_BONUS', 'Referral Bonus'), ('SYSTEM_UPDATE', 'System Update')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
